{{- if .Values.peanut.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peanut.fullname" . }}-config
  labels:
    {{- include "peanut.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.peanut.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.peanut.persistence.size }}
  {{- if .Values.peanut.persistence.storageClass }}
  storageClassName: {{ .Values.peanut.persistence.storageClass }}
  {{- end }}
{{- end }}
